webserver:
    port: 3000
    auth: hellobrankas

database:
    host: localhost
    db: testdb
    username: root
    port: 3306

filetype:
    contenttype: 
    - image/png 
    - image/jpeg 
    - image/gif 
    - image/tiff
    - image/vnd.microsoft.icon 
    - image/x-icon 
    - image/jpvnd.djvu
    - image/svg+xml]