webserver:
    port: 3000
    auth: hellobrankas

database:
    dbname: test.db
    dbpath: sqlite/

filetype:
    contenttype: 
    - image/png 
    - image/jpeg 
    - image/gif 
    - image/tiff
    - image/vnd.microsoft.icon 
    - image/x-icon 
    - image/jpvnd.djvu
    - image/svg+xml]